spring:
  main:
    web-environment: true

logging:
  pattern:
    console: "%date{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC} [%thread] %-5level %40.40logger{40} - [%mdc{REQUEST_ID}][%mdc{CLIENT_ADDRESS}] %msg %n"
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 8081
